name: Code checks
on: 
  pull_request:
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Install pylint
      run: |
        python -m pip install pylint
        python -m pip install pylint-fail-under
    - name: code review 
      run: find . -name '*.py' -print -exec pylint {} \;
        #fails the build if one file has pylint score below 7.0
    - name: Analyse code
      run: |
            for file in */*.py; do pylint "$file" --fail-under=2.0; done 
  
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Install pytest
      run: |
        python -m pip install pytest-cov
    - name: check request
      run: |
        echo "Code finished running"