name: Code checks
on: 
  workflow_dispatch:
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Install pylint
      run: |
        python -m pip install pylint
    - name: Run linting tests
      run: |
        pylint --disable=R,C,W1203 src/model 
  
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
    - name: Install pytest
      run: |
        python -m pip install pytest-cov
    - name: check request
      run: |
        echo "Code finished running"